parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
env:
  es2021: true

plugins:
  - simple-import-sort

rules:
  padding-line-between-statements:
    - off
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  no-console:
    - error
  arrow-parens:
    - error
    - always
  no-else-return:
    - error
    - allowElseIf: false
  jsx-quotes:
    - error
    - prefer-double
  lines-between-class-members:
    - error
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/padding-line-between-statements':
    - error
    - blankLine: always
      prev: '*'
      next:
        - switch
        - class
        - function
        - if
        - return
        - try
        - interface
        - type
