printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: preserve
trailingComma: es5
bracketSpacing: true
arrowParens: always
overrides:
  
files: '*.scss'
  options:
    singleQuote: false